// Real browser pass against a disposable server/database and local bare Git remote.
// Compiles into .ide-lab-dist so verification cannot replace the live server artifact.
const assert = require("node:assert/strict");
const fs = require("node:fs");
const os = require("node:os");
const path = require("node:path");
const { execFileSync } = require("node:child_process");
const Database = require("better-sqlite3");
const { SERVER_ROOT, loadChromium, authPassword, boot, killInstance, shotDir } = require("./lab-harness.cjs");
const PORT = 4361;
const BASE = `http://127.0.0.1:${PORT}`;
const git = (cwd, ...args) => execFileSync("git", args, { cwd, encoding: "utf8", windowsHide: true }).trim();
const wait = async (fn, message) => { for (let n = 0; n < 100; n++) { if (await fn()) return; await new Promise(r => setTimeout(r, 100)); } throw new Error(message); };
let count = 0;
const passed = text => { count++; console.log(`✓ ${text}`); };
async function area(page, value) {
  if (await page.locator('[aria-label="All areas"]').isVisible()) await page.selectOption('[aria-label="All areas"]', value);
  else if (await page.locator('[aria-label="Board area"]').isVisible()) await page.selectOption('[aria-label="Board area"]', value);
  else await page.locator(`.bt-${value}`).click();
}
async function edit(page, text) {
  const native = page.locator('.ide-touch-editor > textarea');
  if (await native.isVisible()) await native.fill(text);
  else { await page.locator('.monaco-editor .view-lines').first().click(); await page.keyboard.press("Control+a"); await page.keyboard.insertText(text); }
}
async function settled(page) {
  await page.waitForFunction(() => !document.querySelector(".gc-activity.busy") && !!document.querySelector(".gc-activity.ok, .gc-activity.err"));
  const failure = await page.locator(".gc-activity.err").count() ? await page.locator(".gc-activity.err").textContent() : "";
  assert.equal(failure, "", failure);
}

(async () => {
  const dataDir = fs.mkdtempSync(path.join(os.tmpdir(), "ggo-ide-lab-"));
  const fixture = fs.mkdtempSync(path.join(os.tmpdir(), "ggo-ide-fixture-"));
  const shots = shotDir(dataDir);
  const work = path.join(fixture, "sample-project");
  const remote = path.join(fixture, "origin.git");
  let browser;
  try {
    execFileSync(process.execPath, [require.resolve("typescript/bin/tsc"), "-p", "tsconfig.json", "--outDir", ".ide-lab-dist"], { cwd: SERVER_ROOT, stdio: "inherit", windowsHide: true });
    git(fixture, "init", "--quiet", "--bare", remote); git(fixture, "clone", "--quiet", remote, work);
    for (const [key, value] of [["user.name", "IDE Lab"], ["user.email", "ide-lab@example.com"], ["commit.gpgsign", "false"], ["core.autocrlf", "false"]]) git(work, "config", key, value);
    fs.writeFileSync(path.join(work, "app.ts"), "const greeting: string = 'hello';\nconsole.log(greeting);\n");
    fs.writeFileSync(path.join(work, "README.md"), "# Sample project\n\nA fixture for the GGO IDE.\n");
    fs.mkdirSync(path.join(work, "src")); fs.writeFileSync(path.join(work, "src", "helper.ts"), "export const helper = 'search needle';\n");
    git(work, "add", "-A"); git(work, "commit", "--quiet", "-m", "initial"); git(work, "branch", "-M", "main"); git(work, "push", "--quiet", "-u", "origin", "main"); git(work, "branch", "feature/spare");
    await boot({ dataDir, port: PORT, entry: path.join(SERVER_ROOT, ".ide-lab-dist", "index.js"), env: { CODEX_WAKE: "off", WORKSPACE_SEARCH_ROOTS: fixture } });
    const db = new Database(path.join(dataDir, "orchestrator.sqlite"));
    db.prepare("INSERT INTO kv(key,value) VALUES('setting_recent_repos',?) ON CONFLICT(key) DO UPDATE SET value=excluded.value").run(JSON.stringify([work]));
    db.prepare("INSERT INTO threads(id,title,state,workspace,brief,raw_prompt,created_at,updated_at) VALUES(?,?,'review',?,?,?, ?,?)").run("ide-lab-task", "Sample project", work, "IDE fixture", "IDE fixture", Date.now(), Date.now()); db.close();
    browser = await loadChromium().launch();
    const context = await browser.newContext({ viewport: { width: 1600, height: 1000 } });
    const page = await context.newPage();
    const errors = [];
    page.on("pageerror", e => errors.push(e.message));
    page.on("console", m => { if (m.type() === "error" && !/Failed to load resource.*(409|400)/.test(m.text())) errors.push(m.text()); });
    page.on("dialog", d => d.accept());
    assert.equal((await page.request.post(`${BASE}/api/login`, { data: { password: authPassword() } })).status(), 200);
    await page.goto(BASE); await page.waitForSelector(".accounts .acct");
    await area(page, "ide"); await page.waitForSelector('[aria-label="IDE workspace"] option:has-text("sample-project")', { state: "attached" });
    const workspaces = await (await page.request.get(`${BASE}/api/ide/workspaces`)).json();
    const ws = workspaces.find(w => w.name === "sample-project"); assert.ok(ws);
    await page.selectOption('[aria-label="IDE workspace"]', ws.id);
    await page.locator('.ide-tree button[title="app.ts"]').click();
    await page.waitForSelector(".monaco-editor .view-lines");
    await edit(page, 'const greeting: number = "wrong";\nconsole.log(greeting);\n');
    await page.waitForSelector(".squiggly-error", { timeout: 30000 });
    passed("Monaco opens real files and TypeScript diagnostics run in a worker");
    await edit(page, "const greeting = 'saved from GGO';\nconsole.log(greeting);\n");
    await page.locator('.ide-save').click();
    await wait(() => fs.readFileSync(path.join(work, "app.ts"), "utf8").includes("saved from GGO"), "Save did not reach disk");
    await page.locator('.ide-tree button[title="README.md"]').click();
    await wait(async () => await page.locator('.ide-tab').count() === 2, "Second editor tab did not open");
    await page.getByRole("tab", { name: "app.ts", exact: true }).click();
    await edit(page, "const greeting = 'draft survives';\n");
    await area(page, "notes"); await area(page, "ide");
    assert.match(await page.locator('.ide-tabs').textContent(), /● app.ts/);
    passed("save reaches disk; multiple tabs and unsaved drafts survive area navigation");
    await page.reload(); await page.waitForSelector(".accounts .acct"); await area(page, "ide");
    await page.waitForSelector(".monaco-editor"); assert.match(await page.locator('.ide-tabs').textContent(), /● app.ts/);
    fs.writeFileSync(path.join(work, "app.ts"), "const greeting = 'external edit';\n");
    await page.locator('.ide-save').click(); await page.waitForSelector('.ide-error');
    assert.match(await page.locator('.ide-error').textContent(), /changed on disk/);
    assert.match(fs.readFileSync(path.join(work, "app.ts"), "utf8"), /external edit/);
    await page.getByRole("button", { name: "Compare disk", exact: true }).click();
    await page.waitForSelector('.ide-compare');
    assert.match(await page.locator('.ide-compare').textContent(), /draft survives/); assert.match(await page.locator('.ide-compare').textContent(), /external edit/);
    await page.getByRole("button", { name: "Reload", exact: true }).click();
    await wait(async () => !(await page.locator('.ide-tabs').textContent()).includes("●"), "Reload did not clear draft");
    passed("reload recovery, external-write conflict, compare and explicit reload preserve disk edits");
    await page.getByRole("button", { name: "Search", exact: true }).click();
    await page.getByLabel("Search workspace", { exact: true }).fill("search needle");
    await page.getByLabel("Search file contents", { exact: true }).check();
    await page.locator('.ide-search button:has-text("src/helper.ts:1")').click();
    await wait(async () => (await page.locator('.ide-breadcrumb').textContent()).includes("src/helper.ts"), "Search result did not open the file");
    passed("workspace content search navigates to a real file and line");
    await page.getByRole("button", { name: "Files", exact: true }).click();
    await page.locator('.ide-tree button[title="src"]').click();
    await page.locator('.ide-tree button[title="src/helper.ts"]').waitFor();
    await page.evaluate(() => document.querySelector('.monaco-editor').dataset.cacheProbe = "resident");
    let repeatReads = 0;
    const readCounter = request => { if (/\/api\/ide\/(tree|file|search)\?/.test(request.url())) repeatReads++; };
    page.on("request", readCounter);
    await page.getByRole("button", { name: "Search", exact: true }).click();
    assert.equal(await page.getByLabel("Search workspace", { exact: true }).inputValue(), "search needle");
    await page.locator('.ide-search button:has-text("src/helper.ts:1")').waitFor({ timeout: 1000 });
    await page.getByRole("button", { name: "Extensions & editor", exact: true }).click();
    await page.getByRole("button", { name: "Files", exact: true }).click();
    await page.locator('.ide-tree button[title="src/helper.ts"]').waitFor({ timeout: 1000 });
    assert.equal(await page.locator('.monaco-editor').getAttribute("data-cache-probe"), "resident");
    assert.equal(repeatReads, 0, "switching tools must not reload files, trees or search");
    page.off("request", readCounter);
    passed("tool switches retain the Monaco instance, expanded folders and search with zero repeat reads");
    await page.locator('.ide-tree button[title="README.md"]').click();
    await page.getByRole("tab", { name: "README.md", exact: true }).waitFor();
    await page.getByRole("button", { name: "Close README.md", exact: true }).click();
    repeatReads = 0; page.on("request", readCounter);
    await page.locator('.ide-tree button[title="README.md"]').click();
    await page.getByRole("tab", { name: "README.md", exact: true }).waitFor({ timeout: 1000 });
    assert.equal(repeatReads, 0, "reopening a recently read file must use the cache");
    page.off("request", readCounter);
    passed("closing and reopening a cached file is immediate without another API read");
    await page.getByRole("button", { name: "Extensions & editor", exact: true }).click();
    await page.locator('.ide-import input').setInputFiles({ name: "test.code-snippets", mimeType: "application/json", buffer: Buffer.from(JSON.stringify({ "Log value": { prefix: "ggolog", scope: "typescript", body: "console.log(${1:value});$0" } })) });
    await page.waitForSelector('.ide-snippet');
    const { zipSync, strToU8 } = require(path.join(SERVER_ROOT, "..", "web", "node_modules", "fflate"));
    const vsix = zipSync({ "extension/package.json": strToU8(JSON.stringify({ name: "sample-snippets", publisher: "ggo-lab", version: "1.0.0", license: "MIT", main: "evil.js", contributes: { snippets: [{ language: "typescript", path: "snippets.json" }] } })), "extension/snippets.json": strToU8(JSON.stringify({ "Log value from VSIX": { prefix: "ggolog", body: "console.log(${1:value});$0" } })), "extension/evil.js": strToU8("globalThis.__vsixExecuted = true") });
    await page.locator('.ide-vsix-import input').setInputFiles({ name: "sample.vsix", mimeType: "application/octet-stream", buffer: Buffer.from(vsix) });
    await page.waitForSelector('.ide-extension-info:has-text("ggo-lab.sample-snippets")');
    assert.match(await page.locator('.ide-extension-info').textContent(), /Unsupported: executable extension code/);
    assert.equal(await page.evaluate(() => globalThis.__vsixExecuted), undefined);
    await page.getByRole("button", { name: "Files", exact: true }).click();
    await page.getByRole("tab", { name: "app.ts", exact: true }).click();
    await edit(page, "ggolog"); await page.keyboard.press("Control+Space");
    await page.waitForSelector('.suggest-widget.visible');
    await page.locator('.suggest-widget.visible .monaco-list-row').filter({ hasText: "ggolog" }).waitFor();
    await page.keyboard.press("Enter");
    await page.locator('.ide-save').click();
    await wait(() => fs.readFileSync(path.join(work, "app.ts"), "utf8").includes("console.log(value)"), "Snippet did not insert");
    passed("VS Code snippet import produces real scoped completion and placeholder insertion");
    await edit(page, "const value = 'Hello from GGO';\nconsole.log(value);\n\nexport function greet(name: string): string {\n  return 'Welcome, ' + name;\n}\n");
    await page.locator('.ide-save').click();
    await wait(() => fs.readFileSync(path.join(work, "app.ts"), "utf8").includes("function greet"), "Final editor content not saved");
    await page.locator('.ide-tree button[title="app.ts"]').waitFor();
    await page.screenshot({ path: path.join(shots, "ide-desktop.png") });
    await page.evaluate(() => document.documentElement.setAttribute("data-theme", "nocturne"));
    await page.screenshot({ path: path.join(shots, "ide-nocturne.png") });
    await page.getByRole("button", { name: "Source control", exact: true }).click();
    await page.waitForSelector('[aria-label="Stage app.ts"]');
    await page.getByLabel("Stage app.ts", { exact: true }).click(); await settled(page);
    assert.equal(git(work, "diff", "--cached", "--name-only"), "app.ts");
    await page.getByLabel("Unstage app.ts", { exact: true }).click(); await settled(page);
    assert.equal(git(work, "diff", "--cached", "--name-only"), "");
    await page.getByLabel("Stage app.ts", { exact: true }).click(); await settled(page);
    await page.locator('.ide-index-file button').filter({ hasText: /^app.ts$/ }).first().click();
    await page.waitForSelector('.ide-index-diff .diff');
    await page.evaluate(() => document.querySelector('.ide-source-control').dataset.cacheProbe = "resident");
    await page.getByRole("button", { name: "Files", exact: true }).click();
    await page.getByRole("button", { name: "Source control", exact: true }).click();
    await page.locator('.ide-index-diff .diff').waitFor({ timeout: 1000 });
    assert.equal(await page.locator('.ide-source-control').getAttribute("data-cache-probe"), "resident");
    passed("returning to Git retains repository state, selection and diff during background refresh");
    await page.getByLabel("Commit summary", { exact: true }).fill("feat: edit through IDE");
    await page.getByRole("button", { name: "Commit 1 staged files", exact: true }).click(); await settled(page);
    assert.equal(git(work, "log", "-1", "--format=%s"), "feat: edit through IDE");
    passed("source control stages, unstages, renders diffs and commits the real index");
    await page.locator('.gc-sync button').filter({ hasText: /Push/ }).click(); await settled(page);
    assert.equal(git(work, "rev-parse", "HEAD"), git(work, "rev-parse", "origin/main"));
    await page.locator('.gc-sync button').filter({ hasText: /Fetch/ }).click(); await settled(page);
    await page.getByRole("tab", { name: "History", exact: true }).click(); await page.waitForSelector('.gc-commit-subject');
    assert.match(await page.locator('.gc-commits').textContent(), /feat: edit through IDE/);
    await page.waitForSelector('.gc-detail-subject:has-text("feat: edit through IDE")');
    await page.waitForSelector('.gc-diff .diff-line.add');
    await wait(async () => /↑0 ↓0/.test(await page.locator('.ide-remote-state').textContent()), "Remote state did not refresh after fetch");
    await page.screenshot({ path: path.join(shots, "ide-git.png") });
    passed("push/fetch use the configured remote; history shows the browser-created commit");
    await page.getByRole("tab", { name: "Changes", exact: true }).click();
    await page.getByLabel("Choose a branch", { exact: true }).click();
    await page.getByRole("button", { name: "New branch…", exact: true }).click();
    await page.locator('.gc-new-branch input').fill("feature/from-ide");
    await page.locator('.gc-new-branch button').click(); await settled(page);
    assert.equal(git(work, "branch", "--show-current"), "feature/from-ide");
    await page.locator('.gc-sync button').filter({ hasText: /Publish/ }).click(); await settled(page);
    assert.equal(git(work, "rev-parse", "--abbrev-ref", "@{u}"), "origin/feature/from-ide");
    await page.locator('.gc-split-main').click(); await settled(page);
    passed("branch creation, publish/upstream setup and pull run through the integrated controls");
    assert.deepEqual(errors, [], errors.join("\n"));
    await context.close();

    for (const width of [320, 390, 768]) {
      const mobile = await browser.newContext({ viewport: { width, height: 844 }, isMobile: true, hasTouch: true });
      const p = await mobile.newPage(); p.on("dialog", d => d.accept());
      await p.request.post(`${BASE}/api/login`, { data: { password: authPassword() } });
      await p.goto(BASE); await p.waitForSelector('.accounts .acct');
      for (const value of ["tasks", "cowork", "notes", "schedules", "supervisor", "ide"]) {
        await area(p, value);
        const geometry = await p.evaluate(() => ({ width: innerWidth, scroll: document.documentElement.scrollWidth, nav: document.querySelector('.mobile-nav').getBoundingClientRect().width }));
        assert.ok(geometry.scroll <= geometry.width + 1, `${value} overflows at ${width}: ${JSON.stringify(geometry)}`);
      }
      await p.waitForSelector('[aria-label="IDE workspace"] option:has-text("sample-project")', { state: "attached" });
      await p.selectOption('[aria-label="IDE workspace"]', ws.id);
      await p.locator('.ide-tree button[title="README.md"]').click();
      await p.waitForSelector('.ide-touch-editor > textarea');
      await edit(p, `# Saved on touch at ${width}px\n`);
      await p.locator('.ide-save').click();
      await wait(() => fs.readFileSync(path.join(work, "README.md"), "utf8").includes(`${width}px`), "Mobile save failed");
      const bounds = await p.locator('.ide-touch-editor > textarea').boundingBox();
      assert.ok(bounds.height >= 150 && bounds.width >= 200, `Unusable touch editor: ${JSON.stringify(bounds)}`);
      await p.screenshot({ path: path.join(shots, `ide-touch-${width}.png`) });
      await p.getByRole("button", { name: "Source control", exact: true }).click();
      await p.getByLabel("Stage README.md", { exact: true }).click(); await settled(p);
      assert.match(git(work, "diff", "--cached", "--name-only"), /README.md/);
      await p.getByLabel("Unstage README.md", { exact: true }).click(); await settled(p);
      await p.getByLabel("Commit summary", { exact: true }).scrollIntoViewIfNeeded();
      assert.ok(await p.getByLabel("Commit summary", { exact: true }).isVisible());
      passed(`${width}px touch: every area reachable without overflow; native editing and save work`);
      await mobile.close();
    }
    console.log(`${count} browser scenarios passed. Screenshots: ${shots}`);
  } finally {
    if (browser) await browser.close();
    killInstance(PORT);
    for (const target of [dataDir, fixture]) { assert.ok(path.resolve(target).startsWith(path.resolve(os.tmpdir())) && path.basename(target).startsWith("ggo-ide-")); fs.rmSync(target, { recursive: true, force: true, maxRetries: 10, retryDelay: 100 }); }
  }
})().catch(e => { console.error(e); process.exitCode = 1; });
